game_env:
  name: "ace_attorney"
  description: "Ace Attorney game environment using retro.Env and GymEnvAdapter."
  env_type: "retro"
  max_steps: 3000
  seed: null
  num_runs: 1

agent:
  name: "ace_attorney_retro_agent"
  model_name: "gpt-4o"
  cache_dir: "cache/retro_ace_attorney" 
  harness: false
  observation_mode: "both" # "vision", "text", or "both"
  
  modules:
    base_module:
    
    perception_module: 

    memory_module:
      max_memory: 15
    
    reasoning_module:
      use_perception: True
      use_memory: True
      use_cot: True 